version: '3.9'
services:
    php-apache-environment:
        container_name: php-apache
        build: .
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:80
    mysql:
        container_name: mysql
        image: mariadb:10.4.27
        restart: always
        command: --lower_case_table_names=1
        volumes:
            - ./data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
        build:
            context: ./phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
